// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJiUnU4DQoJMuEuUkSgQR0VenNmYEg2I',
    appId: '1:98610021883:android:055486e37d2a42645b375e',
    messagingSenderId: '98610021883',
    projectId: 'europe-express',
    databaseURL: 'https://europe-express-default-rtdb.firebaseio.com',
    storageBucket: 'europe-express.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKXnjnurev8AD9DYGRTNyi0w8t5pmoLe4',
    appId: '1:98610021883:ios:65df12bb82ad6b195b375e',
    messagingSenderId: '98610021883',
    projectId: 'europe-express',
    databaseURL: 'https://europe-express-default-rtdb.firebaseio.com',
    storageBucket: 'europe-express.appspot.com',
    iosClientId: '98610021883-46c34aes7mssfalanc4880sakfu8saqi.apps.googleusercontent.com',
    iosBundleId: 'com.asset.digital.europe.express',
  );
}
